# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Bayes_Vacc_cpp <- function(A, X, V, nn, initial_beta, initial_alpha, initial_inv_sigma2_beta, initial_inv_sigma2_alpha, initial_inv_a_beta, mu_alpha, a_alpha = 0.1, b_alpha = 0.1, nu = 1, eta2 = 1, max_iter = 1000L, paras_diff_tol = 1e-6, ELBO_stop = 1L, ELBO_diff_tol = 1e-6, verbose = 0L, save_profile = 1L) {
    .Call(`_VBVaccine_Bayes_Vacc_cpp`, A, X, V, nn, initial_beta, initial_alpha, initial_inv_sigma2_beta, initial_inv_sigma2_alpha, initial_inv_a_beta, mu_alpha, a_alpha, b_alpha, nu, eta2, max_iter, paras_diff_tol, ELBO_stop, ELBO_diff_tol, verbose, save_profile)
}

